config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :dares
  resources :truths
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dare.rb
class Dare < ApplicationRecord
end

app/models/truth.rb
class Truth < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dares_controller.rb
class DaresController < ApplicationController
  before_action :set_dare, only: %i[ show edit update destroy ]

  # GET /dares or /dares.json
  def index
    @dares = Dare.all
  end

  # GET /dares/1 or /dares/1.json
  def show
  end

  # GET /dares/new
  def new
    @dare = Dare.new
  end

  # GET /dares/1/edit
  def edit
  end

  # POST /dares or /dares.json
  def create
    @dare = Dare.new(dare_params)

    respond_to do |format|
      if @dare.save
        format.html { redirect_to dare_url(@dare), notice: "Dare was successfully created." }
        format.json { render :show, status: :created, location: @dare }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dare.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dares/1 or /dares/1.json
  def update
    respond_to do |format|
      if @dare.update(dare_params)
        format.html { redirect_to dare_url(@dare), notice: "Dare was successfully updated." }
        format.json { render :show, status: :ok, location: @dare }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dare.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dares/1 or /dares/1.json
  def destroy
    @dare.destroy

    respond_to do |format|
      format.html { redirect_to dares_url, notice: "Dare was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dare
      @dare = Dare.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dare_params
      params.require(:dare).permit(:text)
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController

end

app/controllers/truths_controller.rb
class TruthsController < ApplicationController
  before_action :set_truth, only: %i[ show edit update destroy ]

  # GET /truths or /truths.json
  def index
    @truths = Truth.all
  end

  # GET /truths/1 or /truths/1.json
  def show
  end

  # GET /truths/new
  def new
    @truth = Truth.new
  end

  # GET /truths/1/edit
  def edit
  end

  # POST /truths or /truths.json
  def create
    @truth = Truth.new(truth_params)

    respond_to do |format|
      if @truth.save
        format.html { redirect_to truth_url(@truth), notice: "Truth was successfully created." }
        format.json { render :show, status: :created, location: @truth }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @truth.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /truths/1 or /truths/1.json
  def update
    respond_to do |format|
      if @truth.update(truth_params)
        format.html { redirect_to truth_url(@truth), notice: "Truth was successfully updated." }
        format.json { render :show, status: :ok, location: @truth }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @truth.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /truths/1 or /truths/1.json
  def destroy
    @truth.destroy

    respond_to do |format|
      format.html { redirect_to truths_url, notice: "Truth was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_truth
      @truth = Truth.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def truth_params
      params.require(:truth).permit(:text)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dares_helper.rb
module DaresHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/truths_helper.rb
module TruthsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dares/_dare.html.erb
<div id="<%= dom_id dare %>">
  <p>
    <strong>Text:</strong>
    <%= dare.text %>
  </p>

</div>

app/views/dares/_form.html.erb
<%= form_with(model: dare) do |form| %>
  <% if dare.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(dare.errors.count, "error") %> prohibited this dare from being saved:</h2>

      <ul>
        <% dare.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :text, style: "display: block" %>
    <%= form.text_area :text %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/dares/edit.html.erb
<h1>Editing dare</h1>

<%= render "form", dare: @dare %>

<br>

<div>
  <%= link_to "Show this dare", @dare %> |
  <%= link_to "Back to dares", dares_path %>
</div>

app/views/dares/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Dares</h1>

<div id="dares">
  <% @dares.each do |dare| %>
    <%= render dare %>
    <p>
      <%= link_to "Show this dare", dare %>
    </p>
  <% end %>
</div>

<%= link_to "New dare", new_dare_path %>

app/views/dares/new.html.erb
<h1>New dare</h1>

<%= render "form", dare: @dare %>

<br>

<div>
  <%= link_to "Back to dares", dares_path %>
</div>

app/views/dares/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @dare %>

<div>
  <%= link_to "Edit this dare", edit_dare_path(@dare) %> |
  <%= link_to "Back to dares", dares_path %>

  <%= button_to "Destroy this dare", @dare, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/page/page.html.erb
<h1>hello </h1>

app/views/truths/_form.html.erb
<%= form_with(model: truth) do |form| %>
  <% if truth.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(truth.errors.count, "error") %> prohibited this truth from being saved:</h2>

      <ul>
        <% truth.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :text, style: "display: block" %>
    <%= form.text_area :text %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/truths/_truth.html.erb
<div id="<%= dom_id truth %>">
  <p>
    <strong>Text:</strong>
    <%= truth.text %>
  </p>

</div>

app/views/truths/edit.html.erb
<h1>Editing truth</h1>

<%= render "form", truth: @truth %>

<br>

<div>
  <%= link_to "Show this truth", @truth %> |
  <%= link_to "Back to truths", truths_path %>
</div>

app/views/truths/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Truths</h1>

<div id="truths">
  <% @truths.each do |truth| %>
    <%= render truth %>
    <p>
      <%= link_to "Show this truth", truth %>
    </p>
  <% end %>
</div>

<%= link_to "New truth", new_truth_path %>

app/views/truths/new.html.erb
<h1>New truth</h1>

<%= render "form", truth: @truth %>

<br>

<div>
  <%= link_to "Back to truths", truths_path %>
</div>

app/views/truths/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @truth %>

<div>
  <%= link_to "Edit this truth", edit_truth_path(@truth) %> |
  <%= link_to "Back to truths", truths_path %>

  <%= button_to "Destroy this truth", @truth, method: :delete %>
</div>

app/views/welcome/index.html.erb
<h1>Hello !</h1>

  <%= link_to "Dares", dares_path %>
  <br/>
  <br/>
  <%= link_to "Truths", truths_path %>